# Logging
wandb_log: true
wandb_project: 'daisy'
wandb_run_name: 'milli-dclm-sweep'
# Torch config
torch.coordinate_descent_tuning: true
# Pretraining configuration
train_shards: "data/dclm_baseline/dclm_baseline_train_*.bin"
target_tokens: 237_568_000
cooldown_frac: 0
learning_rate_schedule: cosine_decay
learning_rate_floor: 0.1
training_sequence_length: 37_120        #  N * 1024; must be divisible by window_block_size
train_attention_window_len: 8192        # largest sliding attention window used during training; must be divisible by window_block_size
# Optimizers configuration
optimizers:
  - type: AdamW
    betas: [0.9, 0.95]
    eps: 1.0e-10
    weight_decay: 0.01
    fused: true
    params:
      - group: head_params
        lr: 0.003464
      - group: embed_params
        lr: 0.110848
      - group: scalar_params
        lr: 0.01299
  - type: Muon
    momentum: 0.95
    weight_decay: 0.01
    params:
      - group: hidden_matrix_params
        lr: 0.025
full_windows: true
# Gradient accumulation
grad_acc_steps: 2
# Evaluations
val_shards:
  - type: "dclm_baseline"
    path: "data/dclm_baseline/dclm_baseline_val_*.bin"
    target_tokens: 20_971_520
    sequence_length: 131_072
val_loss_every_tokens:   11_878_400
# Checkpoints
checkpoint_warmup_tokens:   6_000_000_000     # token warmup before checkpoints
checkpoint_per_n_tokens:     1         # checkpoint interval by tokens
save_checkpoint: false
# Model Definition
model_spec: daisy_milli