# Logging
wandb_log: true
wandb_project: 'daisy'
wandb_run_name: 'nano-dclm'
wandb_group: 'nano-dclm'
# Random seed
seed: 1337
# Torch config
torch.coordinate_descent_tuning: true
# Pretraining configuration
train_shards: "data/dclm_baseline/dclm_baseline_train_*.bin"
target_tokens: 1_000_000_000
cooldown_frac: 1
learning_rate_schedule: linear_decay
learning_rate_floor: 0.1
training_sequence_length: 65_536
train_attention_window_len: 2048
# Optimizers configuration
optimizers:
  - type: AdamW
    betas: [0.9, 0.95]
    eps: 1.0e-10
    weight_decay: 0.01
    fused: true
    params:
      - group: head_params
        lr: 0.003464
      - group: embed_params
        lr: 0.110848
      - group: scalar_params
        lr: 0.01299
  - type: Muon
    momentum: 0.95
    weight_decay: 0.01
    params:
      - group: hidden_matrix_params
        lr: 0.025
full_windows: false
grad_acc_steps: 1 # assumes world_size=8
# Evaluations
val_shards:
  - type: "dclm_baseline"
    path: "data/dclm_baseline/dclm_baseline_val_*.bin"
    target_tokens: 1_966_080
    sequence_length: 131_072
val_loss_every_tokens:    13_107_200
# Checkpoints
checkpoint_warmup_tokens:   1
checkpoint_per_n_tokens:     1
save_checkpoint: true
# Model Definition
model_spec: daisy_nano