# Logging
wandb_log: true
wandb_project: 'daisy-milli'
wandb_run_name: 'milli-pretrain'
# Torch config
torch.coordinate_descent_tuning: true
# Pretraining configuration
train_shards: "data/fineweb-edu/edu_fineweb_train_*.bin"
target_tokens: 18_000_000_000
cooldown_frac: 1
learning_rate_schedule: cosine_decay
learning_rate_floor: 0.1
training_sequence_length: 48_000        #  N * 1024; must be divisible by window_block_size
train_attention_window_len: 8192        # largest sliding attention window used during training; must be divisible by window_block_size
# Optimizers configuration
optimizers:
  - type: AdamW
    betas: [0.9, 0.95]
    eps: 1.0e-10
    weight_decay: 0.0
    fused: true
    params:
      - group: head_params         # "hidden" baseline for Adam
        lr: 0.003464               # unchanged
      - group: embed_params        # LVP âˆšd-rule
        lr: 0.110848               # instead of 0.1732
      - group: scalar_params
        lr: 0.01299                # can stay as-is (LVP is silent)
  - type: Muon
    momentum: 0.95
    weight_decay: 0.0
    params:
      - group: hidden_matrix_params
        lr: 0.02
full_windows: true
# Gradient accumulation
grad_acc_steps: 1 # assumes world_size=8
# Evaluations
val_shards:
  - type: "fineweb-edu"
    path: "data/fineweb-edu/edu_fineweb_val_*.bin"
    target_tokens: 10_485_760
    sequence_length: 131_072
val_loss_every_tokens:    524_288_000 #  = 500 steps
# Checkpoints
checkpoint_warmup_tokens:   12_000_0000_000     # token warmup before checkpoints
checkpoint_per_n_tokens:     1         # checkpoint interval by tokens
save_checkpoint: true
# Model Definition
model_spec: daisy_milli