# Logging
wandb_log: true
wandb_project: 'daisy-tasks'
wandb_run_name: '280m'
# Torch config
torch.coordinate_descent_tuning: true
# Pretraining configuration
train_shards: "data/fineweb-edu/edu_fineweb_train_*.bin"
target_tokens: 100_000_000
cooldown_frac: 0.0
learning_rate_schedule: linear_decay
learning_rate_floor: 0.3
training_sequence_length: 3456        #  N * 1024; must be divisible by window_block_size
train_attention_window_len: 3456        # largest sliding attention window used during training; must be divisible by window_block_size
# Optimizers configuration
optimizers:
  - type: AdamW
    betas: [0.9, 0.95]
    eps: 1.0e-10
    weight_decay: 0.0
    fused: true
    params:
      - group: head_params
        lr: 0.003464
      - group: embed_params
        lr: 0.1732
      - group: scalar_params
        lr: 0.01299
  - type: Muon
    momentum: 0.95
    weight_decay: 0.0
    params:
      - group: hidden_matrix_params
        lr: 0.02
full_windows: false
# Gradient accumulation
grad_acc_steps: 1
# Evaluations
val_shards:
  - type: "fineweb-edu"
    path: "data/fineweb-edu/edu_fineweb_val_*.bin"
    target_tokens: 5_242_880
    sequence_length: 65_536
val_loss_every_tokens:     6_912_000
# Checkpoints
checkpoint_warmup_tokens:   0     # token warmup before checkpoints
checkpoint_per_n_tokens:     0         # checkpoint interval by tokens
save_checkpoint: false
# Model Definition
model_spec: daisy_300m