# Logging
wandb_log: true
wandb_project: 'validations'
wandb_run_name: 'pico-fineweb-edu-single-gpu'
# Torch config
torch.coordinate_descent_tuning: true
# Pretraining configuration
train_shards: "data/fineweb-edu/edu_fineweb_train_*.bin"
target_tokens: 100_000_000
cooldown_frac: 0.0
learning_rate_schedule: linear_decay
learning_rate_floor: 0.01
training_sequence_length: 65_536
train_attention_window_len: 4096
# Optimizers configuration
optimizers:
  - type: AdamW
    betas: [0.9, 0.95]
    eps: 1.0e-10
    weight_decay: 0.0
    fused: true
    params:
      - group: head_params
        lr: 0.003464
      - group: embed_params
        lr: 0.110848
      - group: scalar_params
        lr: 0.01299
  - type: Muon
    momentum: 0.95
    weight_decay: 0.0
    params:
      - group: hidden_matrix_params
        lr: 0.025
full_windows: false
grad_acc_steps: 1
# Evaluations
val_shards:
  - type: "fineweb-edu"
    path: "data/fineweb-edu/edu_fineweb_val_*.bin"
    target_tokens: 41_943_040
    sequence_length: 65_536
val_loss_every_tokens:   3_276_800
# Checkpoints
checkpoint_warmup_tokens:   1_000_000_001
checkpoint_per_n_tokens:     1
save_checkpoint: false
# Model Definition
model_spec: daisy_pico